### ISSUE TITLE
Increase build version on each download

### ISSUE THREAD

**Issue by luisherranz** [worona/publish-native-app-extension-worona#15]

**Comment by luisherranz** [comment]
Hmm... we have a problem with this @Poliuk 

Version number is what we were going to use to distinguish between our own config.xml versions.

What is this for? What is the original problem?

**Comment by Poliuk** [comment]
Itunes connect doesn't allow multiple .ipa uploads if they have the same build number.  For example,  right now it is imposible to change the App Icon, create a new .ipa and replace the old one on itunes connect.

I've already manually updated the config.xml of Worona Travel, because I had to submit several .ipa files.

**Comment by luisherranz** [comment]
Ok maybe the solution is to use minor for their incremental uploads and major for our config.xml changes. Then use only major versions when comparing in chcp.

**Comment by luisherranz** [comment]
I'll implement that
